### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by Aculoss** [Super-Santa/EssentialAddons#31]
This is incompatible with Player Roles. Fabric 1.18.2

**Comment by senseiwells** [comment]
Could you please provide crash report and link to the mod?

**Comment by Aculoss** [comment]
Here you go..

Link to Player Roles: https://www.curseforge.com/minecraft/mc-mods/player-roles-fabric
Or GitHub: https://github.com/NucleoidMC/player-roles

Crash report:

[09:07:00] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[09:07:01] [main/INFO]: Loading 110 mods:
	- adventure-platform-fabric 5.2.0 via floodgate
	- carpet 1.4.66
	- carpet-extra 1.4.64
	- carpet-fixes 1.18.x-1.7.1+v220311
	- carpet-tctc-addition 1.1.8+d0f86ca
	- carpet-tis-addition 1.31.0
	- chunky 1.2.164
	- cloth-api 3.2.64
	- cloth-basic-math 0.6.0 via cloth-api
	- cloth-client-events-v0 3.2.64 via cloth-api
	- cloth-common-events-v1 3.2.64 via cloth-api
	- cloth-config 6.2.57
	- cloth-datagen-api-v1 3.2.64 via cloth-api
	- cloth-utils-v1 3.2.64 via cloth-api
	- cloud 1.5.0 via floodgate
	- cloud_commandframework_cloud-brigadier_ 1.5.0 via cloud
	- cloud_commandframework_cloud-core_ 1.5.0 via cloud
	- cloud_commandframework_cloud-services_ 1.5.0 via cloud
	- com_github_llamalad7_mixinextras 0.0.6 via carpet-fixes
	- com_moandjiezana_toml_toml4j 0.7.2 via jline4mcdsrv
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- compass-commands 1.0.0
	- conditional-mixin 0.1.5 via carpet-fixes
	- config2brigadier 1.1.1 via fabrictailor
	- essentialaddons 1.18.2-1.1.1
	- fabric 0.48.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.5.7+d7c144a860 via fabric
	- fabric-biome-api-v1 8.0.3+801ec85b60 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.2+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.13+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.3.3+691a79b560 via fabric
	- fabric-item-groups-v0 0.3.10+3ac43d9560 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 2.0.2+2540745460 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.0.4+d1027f7d60 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.0.3+40c91ec860 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.2+d1027f7d60 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-handler-api-v1 1.1.14+40c91ec860 via fabric
	- fabric-transfer-api-v1 1.5.14+cca23f9360 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
	- fabricloader 0.13.3
	- fabrictailor 1.8.1
	- ferritecore 4.2.0
	- floodgate 2.1.0-SNAPSHOT
	- geyser-fabric 2.0.2-SNAPSHOT
	- io_leangen_geantyref_geantyref 1.3.11 via cloud
	- java 17
	- jline4mcdsrv 0.3.0
	- krypton 0.1.9
	- lazydfu 0.1.2
	- lithium 0.7.9
	- microconfig 2.2.1 via servshred
	- minecraft 1.18.2
	- minecraft-command-permissions 1.5.0
	- minitweaks 1.2.0
	- more_codecs 0.2.2+1.18 via player_roles
	- net_kyori_adventure-api 4.10.0 via adventure-platform-fabric
	- net_kyori_adventure-key 4.10.0 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.1.0 via adventure-platform-fabric
	- net_kyori_adventure-text-minimessage 4.10.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-gson 4.10.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-plain 4.10.0 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- org_apache_commons_commons-text 1.9 via scarpet-additions
	- org_fusesource_jansi_jansi 2.4.0 via jline4mcdsrv
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_jline_jline 3.21.0 via jline4mcdsrv
	- org_jline_jline-terminal-jansi 3.21.0 via jline4mcdsrv
	- org_yaml_snakeyaml 1.29 via carpet-tis-addition
	- pack 1.0.0
	- pca 0.2.5-alpha+8e41bb1
	- perfectaccuracy 1.2
	- phosphor 0.8.1
	- player_roles 1.5.2
	- player_roles_api 1.5.2 via player_roles
	- rug 1.18.2-1.2.1
	- scarpet-additions 1.4.66
	- servshred 1.0.8
	- servux 0.1.0
	- sgui 1.0.0+1.18.1 via rug
	- totos-carpet-tweaks 1.18-0.2.4
	- worldedit 7.2.11-SNAPSHOT+6143-027a607
	- xpbeacons 7.1
[09:07:01] [main/WARN]: Mod `carpet-fixes` (1.18.x-1.7.1+v220311) does not respect SemVer - comparison support is limited.
[09:07:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/jbake/Desktop/AcuFabric/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[09:07:02] [main/INFO]: Compatibility level set to JAVA_16
[09:07:02] [main/INFO]: Compatibility level set to JAVA_17
[09:07:03] [main/INFO]: Loaded configuration file for Lithium: 100 options available, 2 override(s) found
[09:07:03] [main/WARN]: Reference map 'scarpet-additions-refmap.json' for scarpet-additions.mixins.json could not be read. If this is a development environment you can ignore this message
[09:07:07] [main/WARN]: Mixin malte0811.ferritecore.mixin.threaddetec.PalettedContainerMixin is disabled automatically as lithium is installed
[09:07:07] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[09:07:08] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[09:07:08] [main/WARN]: Error loading class: net/minecraft/class_636 (java.lang.ClassNotFoundException: net/minecraft/class_636)
[09:07:08] [main/WARN]: @Mixin target net.minecraft.class_636 was not found rug.mixins.json:ClientPlayerInteractionManagerMixin
[09:07:08] [main/WARN]: Error loading class: net/minecraft/class_494 (java.lang.ClassNotFoundException: net/minecraft/class_494)
[09:07:08] [main/WARN]: @Mixin target net.minecraft.class_494 was not found rug.mixins.json:LoomScreenMixin
[09:07:08] [main/WARN]: [carpet] detected, disabling UPDATE mixin com.sk89q.worldedit.fabric.mixin.MixinLevelChunkSetBlockHook
[09:07:13] [main/WARN]: Method overwrite conflict for getLanguage in worldedit-fabric.mixins.json:MixinServerPlayer, previously written by carpet.mixins.ServerPlayer_scarpetEventMixin. Skipping method.
[09:07:19] [main/WARN]: Method overwrite conflict for method_5800 in carpet-fixes.mixins.json:itemFixes.ItemEntity_lightningKillsDropsMixin, previously written by carpet.mixins.ItemEntityMixin. Skipping method.
[09:07:27] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$cjn000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[09:07:29] [main/WARN]: @Redirect conflict. Skipping minitweaks.mixins.json:ZombieEntity_AlwaysConvertMixin->@Redirect::forceZombieVillager(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; from mod minitweaks with priority 999, already redirected by rug.mixins.json:ZombieEntityMixin->@Redirect::allowConversion(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; from mod rug with priority 1000
[09:07:29] [main/WARN]: @Redirect conflict. Skipping minitweaks.mixins.json:ZombieEntity_AlwaysConvertMixin->@Redirect::forceZombieVillager(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; from mod minitweaks with priority 999, already redirected by rug.mixins.json:ZombieEntityMixin->@Redirect::allowConversion(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; from mod rug with priority 1000
[09:07:29] [main/WARN]: @Redirect conflict. Skipping minitweaks.mixins.json:ZombieEntity_AlwaysConvertMixin->@Redirect::forceZombieVillager(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; from mod minitweaks with priority 999, already redirected by rug.mixins.json:ZombieEntityMixin->@Redirect::allowConversion(Lnet/minecraft/class_3218;)Lnet/minecraft/class_1267; from mod rug with priority 1000
[09:07:33] [main/WARN]: @Redirect conflict. Skipping minitweaks.mixins.json:PlayerInventory_ItemDespawnMixin->@Redirect::modifyAge(Lnet/minecraft/class_1657;Lnet/minecraft/class_1799;ZZ)Lnet/minecraft/class_1542; from mod minitweaks with priority 999, already redirected by essentialaddons.mixins.json:essentialCarefulDrop.PlayerInventoryMixin->@Redirect::onDropItem(Lnet/minecraft/class_1657;Lnet/minecraft/class_1799;ZZ)Lnet/minecraft/class_1542; from mod essentialaddons with priority 1000
[09:07:34] [main/INFO]: Loaded C2B lib.
[09:07:35] [main/WARN]: @Redirect conflict. Skipping roles.mixins.json:command.ServerCommandSourceMixin->@Redirect::shouldReceiveCommandFeedback(Lnet/minecraft/class_3324;Lcom/mojang/authlib/GameProfile;)Z from mod player_roles with priority 1000, already redirected by essentialaddons.mixins.json:broadcastToAll.ServerCommandSourceMixin->@Redirect::shouldBroadcast(Lnet/minecraft/class_3324;Lcom/mojang/authlib/GameProfile;)Z from mod essentialaddons with priority 1000
[09:07:47] [main/INFO]: Compression will use Java 11, encryption will use Java
[09:07:47] [main/INFO]: Scarpet-additions loaded
[09:07:47] [main/INFO]: [STDOUT]: ServShred is starting
[09:07:48] [main/INFO]: Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@ad43c8d]
[09:07:48] [main/INFO]: WorldEdit for Fabric (version 7.2.11-SNAPSHOT+6143-027a607) is loaded
[09:07:48] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'floodgate'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.3.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingImplementation]: No implementation for Set<FloodgateCommand> was bound.

Requested by:
1  : CommandRegister.registerCommands(CommandRegister.java:56)
      \_ for 1st parameter foundCommands
     at CommandRegister.registerCommands(CommandRegister.java:56)
     at CommandModule.configure(CommandModule.java:42)
      \_ installed by: PostInitializeModule -> FabricCommandModule

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

2) An exception was caught and reported. Message: Mixin transformation of net.minecraft.class_2168 failed
  at PostInitializeModule.configure(PostInitializeModule.java:39)
      \_ installed by: PostInitializeModule -> FabricCommandModule

2 errors

======================
Full classname legend:
======================
CommandModule:        "org.geysermc.floodgate.module.CommandModule"
CommandRegister:      "org.geysermc.floodgate.register.CommandRegister"
FabricCommandModule:  "org.geysermc.floodgate.module.FabricCommandModule"
FloodgateCommand:     "org.geysermc.floodgate.platform.command.FloodgateCommand"
PostInitializeModule: "org.geysermc.floodgate.module.PostInitializeModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:568) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:244) ~[floodgate-fabric.jar:?]
	at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:130) ~[floodgate-fabric.jar:?]
	at org.geysermc.floodgate.FabricMod.onInitialize(FabricMod.java:27) ~[floodgate-fabric.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	... 15 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2168 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
	at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:117) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:106) ~[floodgate-fabric.jar:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409) ~[floodgate-fabric.jar:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:418) ~[floodgate-fabric.jar:?]
	at com.google.inject.AbstractModule.install(AbstractModule.java:106) ~[floodgate-fabric.jar:?]
	at org.geysermc.floodgate.module.PostInitializeModule.configure(PostInitializeModule.java:39) ~[floodgate-fabric.jar:?]
	at com.google.inject.AbstractModule.configure(AbstractModule.java:64) ~[floodgate-fabric.jar:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409) ~[floodgate-fabric.jar:?]
	at com.google.inject.spi.Elements.getElements(Elements.java:108) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:244) ~[floodgate-fabric.jar:?]
	at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:130) ~[floodgate-fabric.jar:?]
	at org.geysermc.floodgate.FabricMod.onInitialize(FabricMod.java:27) ~[floodgate-fabric.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	... 15 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
	at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:117) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:106) ~[floodgate-fabric.jar:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409) ~[floodgate-fabric.jar:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:418) ~[floodgate-fabric.jar:?]
	at com.google.inject.AbstractModule.install(AbstractModule.java:106) ~[floodgate-fabric.jar:?]
	at org.geysermc.floodgate.module.PostInitializeModule.configure(PostInitializeModule.java:39) ~[floodgate-fabric.jar:?]
	at com.google.inject.AbstractModule.configure(AbstractModule.java:64) ~[floodgate-fabric.jar:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409) ~[floodgate-fabric.jar:?]
	at com.google.inject.spi.Elements.getElements(Elements.java:108) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:244) ~[floodgate-fabric.jar:?]
	at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:130) ~[floodgate-fabric.jar:?]
	at org.geysermc.floodgate.FabricMod.onInitialize(FabricMod.java:27) ~[floodgate-fabric.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector shouldReceiveCommandFeedback(Lnet/minecraft/class_3324;Lcom/mojang/authlib/GameProfile;)Z in roles.mixins.json:command.ServerCommandSourceMixin from mod player_roles failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap player-roles-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
	at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:117) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:106) ~[floodgate-fabric.jar:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409) ~[floodgate-fabric.jar:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:418) ~[floodgate-fabric.jar:?]
	at com.google.inject.AbstractModule.install(AbstractModule.java:106) ~[floodgate-fabric.jar:?]
	at org.geysermc.floodgate.module.PostInitializeModule.configure(PostInitializeModule.java:39) ~[floodgate-fabric.jar:?]
	at com.google.inject.AbstractModule.configure(AbstractModule.java:64) ~[floodgate-fabric.jar:?]
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409) ~[floodgate-fabric.jar:?]
	at com.google.inject.spi.Elements.getElements(Elements.java:108) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239) ~[floodgate-fabric.jar:?]
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:244) ~[floodgate-fabric.jar:?]
	at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:130) ~[floodgate-fabric.jar:?]
	at org.geysermc.floodgate.FabricMod.onInitialize(FabricMod.java:27) ~[floodgate-fabric.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	... 15 more

**Comment by Aculoss** [comment]
Please update to 22w16b (1.19)

**Comment by Aculoss** [comment]
Still incompatible with Player Roles
