### ISSUE TITLE
throws an error in 1.19.3

### ISSUE THREAD

**Issue by wh0oo** [Super-Santa/EssentialAddons#58]
I was really looking forward to giving this a go, but its not compatable with 1.19.3,

`[19:16:48] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "com.mojang.brigadier.tree.LiteralCommandNode.createBuilder()" because the return value of "com.mojang.brigadier.tree.CommandNode.getChild(String)" is null
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:199) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.19.3-loader.0.14.13-launcher.0.11.1.jar:0.11.1]
Caused by: java.lang.NullPointerException: Cannot invoke "com.mojang.brigadier.tree.LiteralCommandNode.createBuilder()" because the return value of "com.mojang.brigadier.tree.CommandNode.getChild(String)" is null
        at essentialaddons.commands.CommandGM.register(CommandGM.java:19) ~[essentialaddons-1.19.2-1.1.5.jar:?]
        at essentialaddons.EssentialAddons.registerCommands(EssentialAddons.java:89) ~[essentialaddons-1.19.2-1.1.5.jar:?]
        at carpet.CarpetServer.lambda$registerCarpetCommands$6(CarpetServer.java:150) ~[fabric-carpet-1.19.3-1.4.93+v221230.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at carpet.CarpetServer.registerCarpetCommands(CarpetServer.java:149) ~[fabric-carpet-1.19.3-1.4.93+v221230.jar:?]
        at net.minecraft.class_2170.handler$zzb000$onRegister(class_2170.java:531) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.<init>(class_2170.java:262) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.<init>(class_5350.java:47) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.method_29466(class_5350.java:85) ~[server-intermediary.jar:?]
        at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_43612(Main.java:152) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43498(class_156.java:942) ~[server-intermediary.jar:?]
        at net.minecraft.class_156.method_43499(class_156.java:936) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:150) ~[server-intermediary.jar:?]
        ... 5 more
`

I would love to donate for an updated version?

**Comment by senseiwells** [comment]
You can download the latest version of the mod on modrinth: https://modrinth.com/mod/essentialaddons
