### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by wh0oo** [Super-Santa/EssentialAddons#60]
Hi!

Tested with latest carpet and 1.19.4, server starts, however with a fake player this eventually happens:

`[19:31:36] [Worker-Main-10/INFO]: Loaded 7 recipes
[19:31:36] [Worker-Main-10/INFO]: Loaded 1250 advancements
[19:31:36] [Server thread/ERROR]: Exception stopping the server
java.lang.NoClassDefFoundError: carpet/fakes/ServerPlayerEntityInterface
        at essentialaddons.utils.ConfigFakePlayerData.lambda$getSaveData$1(ConfigFakePlayerData.java:49) ~[essentialaddons-1.19.3-1.2.1.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at essentialaddons.utils.ConfigFakePlayerData.getSaveData(ConfigFakePlayerData.java:48) ~[essentialaddons-1.19.3-1.2.1.jar:?]
        at essentialaddons.utils.Config.saveConfig(Config.java:109) ~[essentialaddons-1.19.3-1.2.1.jar:?]
        at essentialaddons.EssentialAddons.onServerClosed(EssentialAddons.java:92) ~[essentialaddons-1.19.3-1.2.1.jar:?]
        at carpet.CarpetServer.lambda$onServerClosed$10(CarpetServer.java:226) ~[fabric-carpet-1.19.4-1.4.100+v230314.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at carpet.CarpetServer.onServerClosed(CarpetServer.java:226) ~[fabric-carpet-1.19.4-1.4.100+v230314.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zbg000$carpet$serverClosed(MinecraftServer.java:2349) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:536) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:707) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: carpet.fakes.ServerPlayerEntityInterface
        ... 14 more
`

I would/will/can donate to see an update to this!

Thanks!

**Comment by senseiwells** [comment]
This has been updated, you can find it [here](https://modrinth.com/mod/essentialaddons/version/srCjbSnV)
