### ISSUE TITLE
Incompatible with Telekinesis

### ISSUE THREAD

**Issue by sternschnaube** [Super-Santa/EssentialAddons#65]
The mod: https://modrinth.com/plugin/telekinesis

@Redirect conflict. Skipping telekinesis.mixins.json:MinecartMixin from mod telekinesis->@Redirect::redirectDrops(Lnet/minecraft/class_1688;Lnet/minecraft/class_1799;Lnet/minecraft/class_1282;)Lnet/minecraft/class_1542; with priority 1000, already redirected by essentialaddons.mixins.json:essentialCarefulDrop.AbstractMinecartEntityMixin from mod essentialaddons->@Redirect::oDropItems(Lnet/minecraft/class_1688;Lnet/minecraft/class_1799;Lnet/minecraft/class_1282;)Lnet/minecraft/class_1542; with priority 1000
[16:35:36] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[minecraft_server.jar:0.11.2]
Caused by: java.lang.ExceptionInInitializerError
        at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
        ... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1688 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_1802.<clinit>(class_1802.java:792) ~[server-intermediary.jar:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_1802.<clinit>(class_1802.java:792) ~[server-intermediary.jar:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectDrops(Lnet/minecraft/class_1688;Lnet/minecraft/class_1799;Lnet/minecraft/class_1282;)Lnet/minecraft/class_1542; in telekinesis.mixins.json:MinecartMixin from mod telekinesis failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap telekinesis-fabric-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_1802.<clinit>(class_1802.java:792) ~[server-intermediary.jar:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:349) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
        ... 4 more

**Comment by senseiwells** [comment]
This should no longer be an issue, please re-open if it is.
