### ISSUE TITLE
1.0.0 EssentialsAddons [1.17.1 Fabric] Latest Carpet ---- Crash on startup

### ISSUE THREAD

**Issue by red2blue** [Super-Santa/EssentialAddons#8]
9:55:51] [main/WARN]: @Redirect conflict. Skipping essentialaddons.mixins.json:removeWarnMismatchBlockPos.ServerPlayerInteractionManagerMixin->@Redirect::onWarn(Lorg/apache/logging/log4j/Logger;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V with priority 1000, already redirected by polymer.mixins.json:block.ServerPlayerInteractionManagerMixin->@Redirect::noOneCaresAboutMismatch(Lorg/apache/logging/log4j/Logger;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V with priority **1000**
Exception in thread "main" [19:55:51] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[19:55:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:58)
[19:55:51] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[19:55:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:116)
[19:55:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
[19:55:51] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[19:55:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:70)
[19:55:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
[19:55:51] [main/INFO]: [STDERR]:       ... 1 more
[19:55:51] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[19:55:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:55:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[19:55:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:55:51] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[19:55:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
[19:55:51] [main/INFO]: [STDERR]:       ... 2 more
[19:55:51] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[19:55:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
[19:55:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[19:55:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
[19:55:51] [main/INFO]: [STDERR]:       ... 7 more
[19:55:51] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[19:55:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:55:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[19:55:51] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:55:51] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[19:55:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[19:55:51] [main/INFO]: [STDERR]:       ... 9 more
[19:55:51] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[19:55:51] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[19:55:51] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[19:55:51] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[19:55:51] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[19:55:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
[19:55:51] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
[19:55:51] [main/INFO]: [STDERR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[19:55:51] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:120)
[19:55:51] [main/INFO]: [STDERR]:       ... 14 more
[19:55:51] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onWarn(Lorg/apache/logging/log4j/Logger;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V in essentialaddons.mixins.json:removeWarnMismatchBlockPos.ServerPlayerInteractionManagerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap essentialaddons-refmap.json
[19:55:51] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[19:55:51] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[19:55:51] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[19:55:51] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[19:55:51] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[19:55:51] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[19:55:51] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[19:55:51] [main/INFO]: [STDERR]:       at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[19:55:51] [main/INFO]: [STDERR]:       ... 21 more

**Comment by senseiwells** [comment]
Please provide your mods list
